# Generated by Django 5.0.7 on 2024-07-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='papers/pdfs/'),
        ),
    ]
