# Generated by Django 5.0.7 on 2024-07-31 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_researchpaper_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researchpaper',
            name='content',
        ),
    ]
