# Generated by Django 5.0.7 on 2024-08-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_remove_researchpaper_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
