# Generated by Django 5.0.7 on 2024-08-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_researchpaper_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='rating_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='total_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
